/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Input: typeof import('antdv-next').Input
  const Modal: typeof import('antdv-next').Modal
  const message: typeof import('antdv-next').message
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly Input: UnwrapRef<typeof import('antdv-next')['Input']>
    readonly Modal: UnwrapRef<typeof import('antdv-next')['Modal']>
    readonly message: UnwrapRef<typeof import('antdv-next')['message']>
  }
}