/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('antdv-next')['App']
    ABreadcrumb: typeof import('antdv-next')['Breadcrumb']
    ABreadcrumbItem: typeof import('antdv-next')['BreadcrumbItem']
    AButton: typeof import('antdv-next')['Button']
    ACard: typeof import('antdv-next')['Card']
    ACheckbox: typeof import('antdv-next')['Checkbox']
    ACol: typeof import('antdv-next')['Col']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADivider: typeof import('antdv-next')['Divider']
    AEmpty: typeof import('antdv-next')['Empty']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    AInput: typeof import('antdv-next')['Input']
    AInputNumber: typeof import('antdv-next')['InputNumber']
    AInputPassword: typeof import('antdv-next')['InputPassword']
    AModal: typeof import('antdv-next')['Modal']
    APopover: typeof import('antdv-next')['Popover']
    AProgress: typeof import('antdv-next')['Progress']
    ARadio: typeof import('antdv-next')['Radio']
    ARadioGroup: typeof import('antdv-next')['RadioGroup']
    ARow: typeof import('antdv-next')['Row']
    ASegmented: typeof import('antdv-next')['Segmented']
    ASelect: typeof import('antdv-next')['Select']
    ASpaceCompact: typeof import('antdv-next')['SpaceCompact']
    ASpin: typeof import('antdv-next')['Spin']
    AStatistic: typeof import('antdv-next')['Statistic']
    ASwitch: typeof import('antdv-next')['Switch']
    ATable: typeof import('antdv-next')['Table']
    ATabs: typeof import('antdv-next')['Tabs']
    ATag: typeof import('antdv-next')['Tag']
    ATooltip: typeof import('antdv-next')['Tooltip']
    ATree: typeof import('antdv-next')['Tree']
    ChmodModal: typeof import('./components/remote-file/ChmodModal.vue')['default']
    ChownModal: typeof import('./components/remote-file/ChownModal.vue')['default']
    ConnectionHub: typeof import('./components/ConnectionHub.vue')['default']
    DownloadManager: typeof import('./components/DownloadManager.vue')['default']
    FileContextMenu: typeof import('./components/remote-file/FileContextMenu.vue')['default']
    FileEditor: typeof import('./components/FileEditor.vue')['default']
    FileManager: typeof import('./components/FileManager.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RemoteAuditLog: typeof import('./components/remote-file/RemoteAuditLog.vue')['default']
    RemoteDirectoryTree: typeof import('./components/remote-file/RemoteDirectoryTree.vue')['default']
    RemoteFileTable: typeof import('./components/remote-file/RemoteFileTable.vue')['default']
    RemoteFileWorkbench: typeof import('./components/RemoteFileWorkbench.vue')['default']
    RemotePathBar: typeof import('./components/remote-file/RemotePathBar.vue')['default']
    RemoteStatusBar: typeof import('./components/remote-file/RemoteStatusBar.vue')['default']
    RightPanel: typeof import('./components/RightPanel.vue')['default']
    SettingsModal: typeof import('./components/SettingsModal.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SshModal: typeof import('./components/SshModal.vue')['default']
    SshWorkspace: typeof import('./components/SshWorkspace.vue')['default']
    StatusBar: typeof import('./components/StatusBar.vue')['default']
    SystemMonitor: typeof import('./components/SystemMonitor.vue')['default']
    TabManager: typeof import('./components/TabManager.vue')['default']
    Terminal: typeof import('./components/Terminal.vue')['default']
    TopMenu: typeof import('./components/TopMenu.vue')['default']
  }
}
