/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('antdv-next')['App']
    ABreadcrumb: typeof import('antdv-next')['Breadcrumb']
    ABreadcrumbItem: typeof import('antdv-next')['BreadcrumbItem']
    AButton: typeof import('antdv-next')['Button']
    ACheckbox: typeof import('antdv-next')['Checkbox']
    ACol: typeof import('antdv-next')['Col']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADivider: typeof import('antdv-next')['Divider']
    ADropdown: typeof import('antdv-next')['Dropdown']
    AEmpty: typeof import('antdv-next')['Empty']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    AInput: typeof import('antdv-next')['Input']
    AInputNumber: typeof import('antdv-next')['InputNumber']
    AInputPassword: typeof import('antdv-next')['InputPassword']
    AMenu: typeof import('antdv-next')['Menu']
    AModal: typeof import('antdv-next')['Modal']
    AProgress: typeof import('antdv-next')['Progress']
    ARadio: typeof import('antdv-next')['Radio']
    ARadioGroup: typeof import('antdv-next')['RadioGroup']
    ARow: typeof import('antdv-next')['Row']
    ASegmented: typeof import('antdv-next')['Segmented']
    ASelect: typeof import('antdv-next')['Select']
    ASpaceCompact: typeof import('antdv-next')['SpaceCompact']
    ASpin: typeof import('antdv-next')['Spin']
    ASwitch: typeof import('antdv-next')['Switch']
    ATable: typeof import('antdv-next')['Table']
    ATabs: typeof import('antdv-next')['Tabs']
    ATag: typeof import('antdv-next')['Tag']
    ATooltip: typeof import('antdv-next')['Tooltip']
    ATree: typeof import('antdv-next')['Tree']
    AUpload: typeof import('antdv-next')['Upload']
    ConnectionHub: typeof import('./components/ConnectionHub.vue')['default']
    DownloadManager: typeof import('./components/DownloadManager.vue')['default']
    FileEditor: typeof import('./components/FileEditor.vue')['default']
    FileManager: typeof import('./components/FileManager.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RemoteFileWorkbench: typeof import('./components/RemoteFileWorkbench.vue')['default']
    RightPanel: typeof import('./components/RightPanel.vue')['default']
    SettingsModal: typeof import('./components/SettingsModal.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SshModal: typeof import('./components/SshModal.vue')['default']
    SshWorkspace: typeof import('./components/SshWorkspace.vue')['default']
    StatusBar: typeof import('./components/StatusBar.vue')['default']
    SystemMonitor: typeof import('./components/SystemMonitor.vue')['default']
    TabManager: typeof import('./components/TabManager.vue')['default']
    Terminal: typeof import('./components/Terminal.vue')['default']
    TopMenu: typeof import('./components/TopMenu.vue')['default']
  }
}
